### ISSUE TITLE
Why the outputs of the occupancy network need to mutiply -10?

### ISSUE THREAD

**Issue by StevenLiuWen** [autonomousvision/unisurf#1]
Hi, authors,

Thanks for the released codes of this great work. I am a little concerned about why the outputs of the occupancy network need to multiply -10 before the sigmoid function?

https://github.com/autonomousvision/unisurf/blob/224efc73d50acf422edacaebcaf59a8b8ba6d1ff/model/network.py#L124

**Comment by moechsle** [comment]
Hi StevenLiuWen,
the architecture without the sigmoid was initially proposed in IDR (Yariv Neurips 2020) for representing signed distance fields (sdf). The minus is necessary for a correct transformation from sdf to occupancies, as sdfs are negative inside the object. The factor 10 leads to a better/steeper initialization of the occupancies.

**Comment by StevenLiuWen** [comment]
Hi, moechsle, 

Got it. Thanks for your reply.

**Comment by moechsle** [comment]
Thanks, you are welcome.
