### ISSUE TITLE
What is camera_mat in cam to world transform?

### ISSUE THREAD

**Issue by ishikaalunawat** [autonomousvision/unisurf#18]
https://github.com/autonomousvision/unisurf/blob/224efc73d50acf422edacaebcaf59a8b8ba6d1ff/model/common.py#L240

Hi, I am trying to run my own dataset on your model. As mentioned in previous issues you have claimed to use the [IDR Data Convention](https://github.com/lioryariv/idr/blob/main/DATA_CONVENTION.md) but their code/they do not mention any `camera_mat` in their datasets. They only have `world_mat` and `scale_mat` for each sample.

If `K` is the camera intrinsics matrix (camera coordinates -> pixels) and `[R|t]` is the extrinsics matrix (world -> camera coordinates) then according to the IDR data convention, `world_mat = K * [R|t] ` and consecutively, the pixel to world should be:
(assume scale_mat = identity and I have a world_mat defined)

`p_world = inv(scale_mat) @ inv(world_mat) @ pixels` 

What does the `camera_mat` mean here and how have you generated it?

**Comment by FreddieRao** [comment]
Did you figure it out? I'm super confused. Would you mind please sharing the soultion?

**Comment by ishikaalunawat** [comment]
![EE0DED9E-BC82-4D19-9262-73D6FCEC0DC6](https://user-images.githubusercontent.com/63252702/186563116-69da12d7-0e5a-4c2e-b412-ff5124b76401.png)

Hey I went through their code and found that they don’t fully follow the IDR format.
- `world_mat` is the 4x4 extrinsics matrix
- `scale_mat` is a 4x4 scaling matrix if any
- `camera_mat` is the 3x3 intrinsics matrix appended with homogeneous coordinate to get a 4x4 matrix

Hope this helps :)
