### ISSUE TITLE
numpy/arrayobject.h: No such file or directory

### ISSUE THREAD

**Issue by bring728** [autonomousvision/unisurf#3]
This error occurred while compiling the extension module.

---------------------------------------------------------------------------------
python setup.py build_ext --inplace
running build_ext
/data/happily/anaconda3/envs/unisurf/lib/python3.9/site-packages/torch/utils/cpp_extension.py:381: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
  warnings.warn(msg.format('we could not find ninja.'))
building 'utils.libmise.mise' extension
gcc -pthread -B /data/happily/anaconda3/envs/unisurf/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /data/happily/anaconda3/envs/unisurf/include -fPIC -O2 -isystem /data/happily/anaconda3/envs/unisurf/include -fPIC -I/data/happily/anaconda3/envs/unisurf/include/python3.9 -c utils/libmise/mise.cpp -o build/temp.linux-x86_64-3.9/utils/libmise/mise.o -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE="_gcc" -DPYBIND11_STDLIB="_libstdcpp" -DPYBIND11_BUILD_ABI="_cxxabi1011" -DTORCH_EXTENSION_NAME=mise -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
utils/libmise/mise.cpp:648:10: fatal error: numpy/arrayobject.h: No such file or directory
 #include "numpy/arrayobject.h"
          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
error: command '/usr/bin/gcc' failed with exit code 1
---------------------------------------------------------------------------------

How can I fix this?

**Comment by furaga** [comment]
In my case, I added ` include_dirs=[numpy_include_dir]` to mise_module, and the error was fixed

```
[setup.py]

# mise (efficient mesh extraction)
mise_module = Extension(
    'utils.libmise.mise',
    sources=[
        'utils/libmise/mise.pyx'
    ],
    include_dirs=[numpy_include_dir]   <-------- ADD THIS!
)
```

**Comment by ZipengFeng** [comment]
I sovled this problem by:

`sudo ln -s /usr/local/lib/python3.8/dist-packages/numpy/core/include/numpy/ /usr/include/numpy`

as https://stackoverflow.com/questions/14657375/cython-fatal-error-numpy-arrayobject-h-no-such-file-or-directory described.

**Comment by bring728** [comment]
thank you for helping me!
